import type { Listing } from "./types";

const u = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1600&q=80`;

export const LISTINGS: Listing[] = [
  {
    id: "1",
    slug: "inani-cliff-suite",
    category: "stays",
    title: "Inani Cliff Suite",
    location: "Inani, Cox's Bazar",
    place: "Cox's Bazar",
    description:
      "Cliffside sanctuary with uninterrupted ocean views, private deck and refined coastal living.",
    rating: 4.8,
    reviewCount: 126,
    images: [
      u("photo-1611892440504-42a792e24d32"),
      u("photo-1582719478250-c89cae4dc85b"),
      u("photo-1571896349842-33c89424de2d"),
      u("photo-1520250497591-112f2f40a3f4"),
      u("photo-1566073771259-6a8506099945"),
    ],
    included: ["Ocean view", "Breakfast included", "Infinity pool access", "Free cancellation"],
    beachfront: true,
    familyRooms: true,
    invoiceReady: true,
    kidsAllowed: true,
    soloFriendly: true,
    freeCancellation: true,
    cancelUntilDays: 2,
    distanceKm: 0.2,
    baseUnit: 8000,
    featured: true,
    familyNotes: ["Cot available on request", "Children under 5 stay free (with existing bedding)"],
    corporateNotes: ["Invoice PDF available after payment", "Billing email accepted at checkout"],
    soloNotes: ["Quiet wing available on request"],
    houseRules: ["No smoking", "No pets", "Check-in 2:00 PM", "Check-out 11:00 AM"],
  },
  {
    id: "2",
    slug: "oceanview-beach-resort",
    category: "stays",
    title: "Oceanview Beach Resort & Spa",
    location: "Cox's Bazar Beach",
    place: "Cox's Bazar",
    description: "Beachfront resort with spa, family rooms and calm evening light over the bay.",
    rating: 4.7,
    reviewCount: 214,
    images: [u("photo-1564501049412-61c2a3083791"), u("photo-1551882547-ff40c63fe5fa")],
    included: ["Beachfront", "Breakfast", "Spa access", "Free cancellation"],
    beachfront: true,
    familyRooms: true,
    invoiceReady: true,
    kidsAllowed: true,
    freeCancellation: true,
    cancelUntilDays: 3,
    distanceKm: 0.1,
    baseUnit: 18500,
    featured: true,
    familyNotes: ["Family rooms", "Kids club weekends"],
    corporateNotes: ["Invoice ready"],
    houseRules: ["No smoking", "Check-in 2:00 PM"],
  },
  {
    id: "3",
    slug: "sea-pearl-cottage",
    category: "stays",
    title: "Sea Pearl Cottage",
    location: "Inani, Cox's Bazar",
    place: "Cox's Bazar",
    description: "Low-key cottage steps from the sand with flexible cancellation.",
    rating: 4.5,
    reviewCount: 89,
    images: [u("photo-1564013799919-ab600027ffc6"), u("photo-1600585154340-be6161a56a0c")],
    included: ["Kitchenette", "Free cancellation", "Beach path"],
    beachfront: true,
    familyRooms: true,
    soloFriendly: true,
    kidsAllowed: true,
    freeCancellation: true,
    cancelUntilDays: 4,
    distanceKm: 0.8,
    baseUnit: 6200,
    featured: true,
    familyNotes: ["Family room layout"],
    houseRules: ["Quiet hours after 10 PM"],
  },
  {
    id: "4",
    slug: "patenga-view-hotel",
    category: "stays",
    title: "Patenga View Hotel",
    location: "Patenga, Chattogram",
    place: "Chattogram",
    description: "City-coast hotel with invoice-ready stays for business trips.",
    rating: 4.9,
    reviewCount: 301,
    images: [u("photo-1542314831-068cd1dbfeeb"), u("photo-1618773928121-c32242e63f39")],
    included: ["City view", "Breakfast", "Desk workspace"],
    invoiceReady: true,
    kidsAllowed: true,
    freeCancellation: false,
    cancelUntilDays: 0,
    distanceKm: 1.4,
    baseUnit: 9500,
    corporateNotes: ["Invoice ready", "Late checkout on request"],
    houseRules: ["No smoking"],
  },
  {
    id: "5",
    slug: "inani-beach-house",
    category: "stays",
    title: "Inani Beach House",
    location: "Inani, Cox's Bazar",
    place: "Cox's Bazar",
    description: "Airy beach house with family rooms and morning ocean light.",
    rating: 4.6,
    reviewCount: 128,
    images: [u("photo-1600596542815-ffad4c1539a9"), u("photo-1600607687939-ce8a6c25118c")],
    included: ["Family rooms", "Kitchen", "Free cancellation"],
    beachfront: true,
    familyRooms: true,
    kidsAllowed: true,
    freeCancellation: true,
    cancelUntilDays: 3,
    distanceKm: 0.4,
    baseUnit: 11000,
    familyNotes: ["Connecting rooms available"],
    houseRules: ["No parties"],
  },
  {
    id: "6",
    slug: "laboni-point-suites",
    category: "stays",
    title: "Laboni Point Suites",
    location: "Laboni, Cox's Bazar",
    place: "Cox's Bazar",
    description: "Quiet suites near Laboni with solo-friendly rates.",
    rating: 4.4,
    reviewCount: 76,
    images: [u("photo-1631049307264-da0ec9d70304"), u("photo-1590490360182-c33d57733427")],
    included: ["Solo-friendly", "Breakfast", "Free cancellation"],
    soloFriendly: true,
    kidsAllowed: false,
    freeCancellation: true,
    cancelUntilDays: 2,
    distanceKm: 0.6,
    baseUnit: 7200,
    soloNotes: ["Designed for one traveler"],
    houseRules: ["Adults only"],
  },
  {
    id: "7",
    slug: "himchari-ridge-lodge",
    category: "stays",
    title: "Himchari Ridge Lodge",
    location: "Himchari, Cox's Bazar",
    place: "Cox's Bazar",
    description: "Hilltop lodge above the coast with invoice-ready corporate stays.",
    rating: 4.7,
    reviewCount: 95,
    images: [u("photo-1505693416388-ac5ce068fe85"), u("photo-1584132967334-10e028bd69f7")],
    included: ["Ridge views", "Breakfast", "Invoice ready"],
    invoiceReady: true,
    familyRooms: true,
    kidsAllowed: true,
    freeCancellation: true,
    cancelUntilDays: 5,
    distanceKm: 2.1,
    baseUnit: 8900,
    featured: false,
  },
  {
    id: "8",
    slug: "kolatoli-garden-inn",
    category: "stays",
    title: "Kolatoli Garden Inn",
    location: "Kolatoli, Cox's Bazar",
    place: "Cox's Bazar",
    description: "Garden courtyard inn a short walk from the beach.",
    rating: 4.3,
    reviewCount: 54,
    images: [u("photo-1522708323590-d24dbb6b0267"), u("photo-1502672260266-1c1ef2d93688")],
    included: ["Garden", "Free cancellation"],
    beachfront: false,
    familyRooms: true,
    kidsAllowed: true,
    freeCancellation: true,
    cancelUntilDays: 2,
    distanceKm: 1.0,
    baseUnit: 5400,
  },
  {
    id: "9",
    slug: "sylhet-waterfall-day-trip",
    category: "day-trips",
    title: "Sylhet waterfall day trip",
    location: "Sylhet",
    place: "Sylhet",
    description: "Guided day trip to forest waterfalls with transport and lunch.",
    rating: 4.8,
    reviewCount: 412,
    images: [u("photo-1432405972618-c60b0225b8f9"), u("photo-1501785888041-af3ef285b470")],
    included: ["Guide", "Transport", "Lunch", "Free cancellation"],
    freeCancellation: true,
    cancelUntilDays: 1,
    durationHours: 8,
    baseUnit: 3250,
    featured: true,
    familyNotes: ["Suitable for ages 6+"],
    kidsAllowed: true,
    soloFriendly: true,
    invoiceReady: true,
  },
  {
    id: "10",
    slug: "sundarbans-boat-day",
    category: "day-trips",
    title: "Sundarbans boat day",
    location: "Khulna",
    place: "Khulna",
    description: "Day cruise through mangrove channels with naturalist guide.",
    rating: 4.6,
    reviewCount: 188,
    images: [u("photo-1507525428034-b723cf961d3e"), u("photo-1469474968028-56623f02e42e")],
    included: ["Boat", "Guide", "Snacks"],
    freeCancellation: true,
    cancelUntilDays: 2,
    durationHours: 9,
    baseUnit: 4800,
    kidsAllowed: true,
    invoiceReady: true,
  },
  {
    id: "11",
    slug: "saint-martin-snorkel",
    category: "recreation",
    title: "Saint Martin snorkel session",
    location: "Saint Martin's Island",
    place: "Saint Martin",
    description: "Half-day snorkel with gear and instructor on clear reef pockets.",
    rating: 4.7,
    reviewCount: 156,
    images: [u("photo-1544551763-46a013bb70d5"), u("photo-1500375592092-40eb2168fd21")],
    included: ["Gear", "Instructor", "Transfer from jetty"],
    freeCancellation: true,
    cancelUntilDays: 1,
    durationHours: 3,
    baseUnit: 2900,
    soloFriendly: true,
    kidsAllowed: true,
  },
  {
    id: "12",
    slug: "cox-surf-lesson",
    category: "recreation",
    title: "Cox's Bazar surf lesson",
    location: "Cox's Bazar",
    place: "Cox's Bazar",
    description: "Beginner surf lesson on Laboni break with board included.",
    rating: 4.5,
    reviewCount: 67,
    images: [u("photo-1502680390469-be75c86b636f"), u("photo-1455264745730-cb3b38299ff6")],
    included: ["Board", "Wetsuit", "Coach"],
    freeCancellation: true,
    cancelUntilDays: 1,
    durationHours: 2,
    baseUnit: 2200,
    soloFriendly: true,
    kidsAllowed: false,
  },
];

export function getListing(category: string, slug: string) {
  return LISTINGS.find((l) => l.category === category && l.slug === slug);
}

export function byCategory(category: string) {
  return LISTINGS.filter((l) => l.category === category);
}

export function featuredListings() {
  return LISTINGS.filter((l) => l.featured);
}

export function categoryHasInventory(category: string) {
  return LISTINGS.some((l) => l.category === category);
}

export function makeBookingRef() {
  return `ATL-${Math.floor(100000 + Math.random() * 900000)}`;
}
